openapi: 3.0.0
info:
  version: 1.0.0
  title: Taxi Locator
  x-ibm-name: taxi-locator
servers:
  - url: /taxi-locator
x-ibm-configuration:
  properties:
    target-url:
      value: 'http://eem-demo-rest-api.cp4i-apic.svc:1880/api/v1/findtaxis'
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blocklist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
paths:
  /:
    get:
      summary: Find taxis in a given location
      operationId: findTaxis
      parameters:
        - name: lat
          in: query
          description: latitude
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: longitude
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                required:
                  - taxis
                properties:
                  taxis:
                    type: array
                    items:
                      type: integer
                      format: int32
components:
  securitySchemes:
    clientID:
      type: apiKey
      in: header
      name: X-IBM-Client-Id
security:
  - clientID: []
