openapi: 3.0.0
info:
  version: 1.0.0
  title: Taxi Messaging
  x-ibm-name: taxi-messaging
  description: ''
servers:
  - url: /taxi-messaging
x-ibm-configuration:
  properties:
    target-url:
      value: 'http://eem-demo-rest-api.cp4i-apic.svc:1880/api/v1/taxialert'
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blocklist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
paths:
  /:
    post:
      summary: Send a message to taxi drivers
      operationId: taxiAlert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - taxis
                - message
              properties:
                taxis:
                  type: array
                  items:
                    type: integer
                    format: int32
                message:
                  type: string
      responses:
        '201':
          description: message sent
          content:
            application/json:
              schema:
                type: object
                required:
                  - sent
                properties:
                  sent:
                    type: string
components:
  securitySchemes:
    clientID:
      type: apiKey
      in: header
      name: X-IBM-Client-Id
security:
  - clientID: []
